typography_spectrum: 0.41814795788377523
color:
  brandStrength: 0.06773688108660281
  lightness: 0.35482677607797086
  saturation: 0.29021378164179623
  rhythmicContrast: 0.5281849226448685
  brandColors:
    - '#88A825'
    - '#35203B'
    - '#911146'
    - '#CF4A30'
    - '#ED8C2B'
layout_spectrum: 0.23590830736793578
name: DesignFarm
navigation:
  - id: thegrid.ai/designfarm-enterprises/home
    url: thegrid.ai/designfarm-enterprises/home
    name: Home
    type: external
  - id: >-
      https://login.yahoo.com/?.src=ym&.intl=us&.lang=en-US&.done=https%3a//mail.yahoo.com
    url: >-
      https://login.yahoo.com/?.src=ym&.intl=us&.lang=en-US&.done=https%3a//mail.yahoo.com
    name: facebook
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1651f70b-42cd-4614-a6cd-6e39ec944816.ico
title: '| Logos |'
